### PR TITLE
Types: Add support for floats

### PR DESCRIPTION
**Pull request by PoustouFlan**
This tries to implement a type dedicated to floating numbers in iorgen.
A use case could be, for instance, precise coordinates in input for geometry problems.

Whole numbers typed float needs to be written `13.0`. No leading or trailing zeroes allowed. Up to 15 digits after the floating point allowed I guess ?

Implemented languages (not tested = need to regenerate samples and check them)
- [ ] C++
- [ ] C
- [ ] C#
- [ ] D
- [x] Go (not tested)
- [ ] Haskell
- [ ] Java
- [ ] Javascript
- [ ] Julia
- [ ] Lua
- [ ] Ocaml
- [ ] Pascal
- [ ] Perl
- [ ] Php
- [ ] Prolog
- [x] Python
- [ ] Ruby
- [x] Rust (not tested)
- [ ] Scheme

### CODE REVIEW

**Comment by rissson** [comment]
Can you add a test for float type?

**Comment by PoustouFlan** [comment]
Manually formatted lines containing multiple types seem to be implemented, but neither tester nor appropriately validated.
I added a test for this, which means the validator must also be modified!

**Comment by Shaac** [comment]
Hello,

Thanks for the PR. I won’t I have to review it in detail before I come back from vacation in 2 weeks, but here are some general thoughts.

This implementation seems good, it only leaks a new type to the languages generators, which is exactly what we want. There might be a few tweaks here and there to make for the internal implementation, but the interface is good.

Now for all the languages, the implementation itself should not be too long. We can see it in the 3 already implemented, it’s mostly adding a new case similar to the `INT` one. So strictly implementing the reader should not take very long. I can do it for most languages if needed. But there are still two complications we need to consider.

First issue is: are all the floats in all languages the same? Floating point could be implemented several ways. I guess this is mostly defined by the processor so probably all languages will use the same floats, but still we may have to check. I know for instance Ocaml does strange thinks like removing an available bit for its integers or somethings. We probably need to test for extreem floats (very big, or very close to 0), and maybe give constraints on the floats we can use in iorgen (a maximum value, and a maximum numbers of digits) to be safe.

The other issue is the reprint. For testing iorgen itself, all generators have a reprint method: they will reprint what there are given in input, and there by comparing input and output we can be pretty sure that the parser is working. So it’s like `a = input(); print(a)`. This works well for ints, but not so much for floats, because floats are several representations: `0 == 0.0` and `0.03 == 1e-03`. And also most languages do not show all digits by default, we have to specify it. The most annoying part would probably be to add a `.0` if the float is also an integer (python does that automatically, but I doubt many other languages do it). So sadly, I think the reprint method will be more painful to write than the parser in several languages.

Now for the testing of the current implementations. That’s simple. There is a `regenerate.py` script. Here it won’t work out of the box because some of the old parsers will crash if given a float. So just add `if language.extension not in ("py", "rs", "go"): continue` at the beginning of the for loop. Then you can run `./test.py -l py -l rs -l go`.

We can see it fails for go and rust. Rust does not compile because the struct derive from Eq, Ord and Hash which are not defined for floats (so maybe we should just remove this derive if the struct contains floats). And go does not pass the test because of the reprint issue I mentioned earlier (`0.0` is reprinted to `0`, and `9.0987654321` to `9.098765`. I expect once rust compile it will have a similar issue.

**Comment by kolowy** [comment]
Migrated to https://gitlab.com/prologin/tech/tools/iorgen/-/merge_requests/37

**Pull request closed without merging**
